services:
  - type: web
    name: engineering-ai-coach-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: engineering-ai-coach-db
          property: connectionString
      - key: PORT
        value: 10000
    healthCheckPath: /health

databases:
  - name: engineering-ai-coach-db
    databaseName: engineering_ai_coach
    user: coach_user